### ISSUE TITLE
성별, 생년월일, 연령대 정보를 DB에 저장하고, Frontend에 정보를 반환하도록 코드 수정본 배포

### ISSUE THREAD

**Issue by cipp00h** [ssap-rainbow/SSAP-BackEnd#12]
## 작업 사항

> 사용자가 카카오 로그인 시 선택 동의를 받아 성별, 생년월일, 연령대 정보를 DB에 저장하고, Frontend에 정보를 반환하도록 코드 수정본 배포

## To-do
- [ ] 성별 DB 저장
- [ ] 생년월일 DB 저장
- [ ] 연령대 DB 저장

## 기타사항

> 기타 사항을 작성해주세요
